/**
 * User prompts for different field types
 * These are the instructions sent to the AI for generating content
 */

type FieldType =
  | "currentFinancialSituation"
  | "employmentCircumstances"
  | "reasonForApplying";

export function getUserPrompt(
  fieldType: FieldType,
  language: "en" | "ar",
  context: string
): string {
  const prompts = {
    en: {
      currentFinancialSituation: `Write ONLY the description of the current financial situation and challenges for a social support application. Write in first person ("I", "my", "me") as if you are the applicant speaking about yourself.${context}\n\nCRITICAL REQUIREMENTS:\n- Write in first person: Use "I", "my", "me" throughout. Example: "I am facing financial difficulties..." not "The applicant is facing..."\n- Start immediately with the financial situation description. No greetings, no "Hello", no "Hi", no introductions, no religious phrases\n- Write 2-3 paragraphs of content only\n- Be respectful, honest, and direct\n- Focus on factual details about financial difficulties, expenses, and challenges based on the provided context (age, marital status, dependents, employment, income, housing)\n- Use only English\n- Personalize the content using the provided context (age, gender, marital status, dependents, employment status, income, housing status)\n- End when the description is complete. No closing phrases, no "Thank you", no conclusions\n- Your response must be ONLY the requested content written in first person, nothing else`,
      employmentCircumstances: `Write ONLY the description of the employment circumstances and work situation for a social support application. Write in first person ("I", "my", "me") as if you are the applicant speaking about yourself.${context}\n\nCRITICAL REQUIREMENTS:\n- Write in first person: Use "I", "my", "me" throughout. Example: "I am currently employed..." not "The applicant is currently employed..."\n- Start immediately with the employment circumstances description. No greetings, no "Hello", no "Hi", no introductions, no religious phrases\n- Write 2-3 paragraphs of content only\n- Be respectful, honest, and direct\n- Focus on factual details about work situation, job status, and employment challenges based on the provided context (age, employment status, income, dependents)\n- Use only English\n- Personalize the content using the provided context (age, gender, employment status, income, dependents, marital status)\n- End when the description is complete. No closing phrases, no "Thank you", no conclusions\n- Your response must be ONLY the requested content written in first person, nothing else`,
      reasonForApplying: `Write ONLY the description of the reason for applying for social support. Write in first person ("I", "my", "me") as if you are the applicant speaking about yourself.${context}\n\nCRITICAL REQUIREMENTS:\n- Write in first person: Use "I", "my", "me" throughout. Example: "I am applying because..." not "The applicant is applying because..."\n- Start immediately with the reason for applying. No greetings, no "Hello", no "Hi", no introductions, no religious phrases\n- Write 2-3 paragraphs of content only\n- Be respectful, honest, and direct\n- Focus on factual details about why support is needed based on the provided context (financial situation, employment, family circumstances, age, dependents)\n- Use only English\n- Personalize the content using the provided context (age, gender, marital status, dependents, employment status, income, housing status, financial situation)\n- End when the description is complete. No closing phrases, no "Thank you", no conclusions\n- Your response must be ONLY the requested content written in first person, nothing else`,
    },
    ar: {
      currentFinancialSituation: `اكتب فقط وصف الوضع المالي الحالي والتحديات المالية للمتقدم لطلب دعم اجتماعي. اكتب بصيغة المتكلم ("أنا"، "لي"، "عندي") كما لو كنت المتقدم يتحدث عن نفسه.${context}\n\nمتطلبات مهمة جداً:\n- اكتب بصيغة المتكلم: استخدم "أنا"، "لي"، "عندي" في جميع أنحاء النص. مثال: "أواجه صعوبات مالية..." وليس "يواجه المتقدم صعوبات مالية..."\n- ابدأ مباشرة بوصف الوضع المالي. لا تحيات، لا "مرحباً"، لا "أهلاً"، لا مقدمات، لا عبارات دينية\n- اكتب فقرتين إلى ثلاث فقرات من المحتوى فقط باللغة العربية الفصحى\n- كن واقعياً ومحدداً: اذكر التحديات المالية الحقيقية، المصروفات، الديون، أو الصعوبات المالية بناءً على السياق المقدم (العمر، الحالة الاجتماعية، عدد المعالين، التوظيف، الدخل، السكن)\n- استخدم السياق المقدم (العمر، النوع، الحالة الاجتماعية، عدد المعالين، حالة التوظيف، الدخل الشهري، حالة السكن) لتخصيص المحتوى\n- اكتب بأسلوب رسمي ومحترم يناسب طلب الدعم الاجتماعي\n- ركز على التفاصيل الواقعية والظروف الحقيقية\n- لا تستخدم الإنجليزية أبداً\n- أنهِ عندما ينتهي الوصف. لا عبارات ختامية، لا "شكراً"، لا خاتمة\n- يجب أن يكون ردك فقط المحتوى المطلوب مكتوباً بصيغة المتكلم، لا شيء آخر`,
      employmentCircumstances: `اكتب فقط وصف ظروف التوظيف والوضع الوظيفي للمتقدم لطلب دعم اجتماعي. اكتب بصيغة المتكلم ("أنا"، "لي"، "عندي") كما لو كنت المتقدم يتحدث عن نفسه.${context}\n\nمتطلبات مهمة جداً:\n- اكتب بصيغة المتكلم: استخدم "أنا"، "لي"، "عندي" في جميع أنحاء النص. مثال: "أنا أعمل حالياً..." وليس "يعمل المتقدم حالياً..."\n- ابدأ مباشرة بوصف ظروف التوظيف. لا تحيات، لا "مرحباً"، لا "أهلاً"، لا مقدمات، لا عبارات دينية\n- اكتب فقرتين إلى ثلاث فقرات من المحتوى فقط باللغة العربية الفصحى\n- كن واقعياً ومحدداً: اذكر الوضع الوظيفي الحالي، نوع العمل، ساعات العمل، أو التحديات في العمل بناءً على السياق المقدم (العمر، حالة التوظيف، الدخل، عدد المعالين)\n- استخدم السياق المقدم (العمر، النوع، حالة التوظيف، الدخل، عدد المعالين، الحالة الاجتماعية) لتخصيص المحتوى\n- اكتب بأسلوب رسمي ومحترم يناسب طلب الدعم الاجتماعي\n- ركز على التفاصيل الواقعية والظروف الحقيقية\n- لا تستخدم الإنجليزية أبداً\n- أنهِ عندما ينتهي الوصف. لا عبارات ختامية، لا "شكراً"، لا خاتمة\n- يجب أن يكون ردك فقط المحتوى المطلوب مكتوباً بصيغة المتكلم، لا شيء آخر`,
      reasonForApplying: `اكتب فقط وصف سبب التقديم للحصول على الدعم الاجتماعي. اكتب بصيغة المتكلم ("أنا"، "لي"، "عندي") كما لو كنت المتقدم يتحدث عن نفسه.${context}\n\nمتطلبات مهمة جداً:\n- اكتب بصيغة المتكلم: استخدم "أنا"، "لي"، "عندي" في جميع أنحاء النص. مثال: "أتقدم بطلب لأن..." وليس "يتقدم المتقدم بطلب لأن..."\n- ابدأ مباشرة بذكر سبب التقديم. لا تحيات، لا "مرحباً"، لا "أهلاً"، لا مقدمات، لا عبارات دينية\n- اكتب فقرتين إلى ثلاث فقرات من المحتوى فقط باللغة العربية الفصحى\n- كن واقعياً ومحدداً: اذكر الأسباب الحقيقية والحاجة للدعم (صعوبات مالية، ظروف عائلية، ظروف صحية، إلخ) بناءً على السياق المقدم (الوضع المالي، التوظيف، الظروف العائلية، العمر، عدد المعالين)\n- استخدم السياق المقدم (العمر، النوع، الحالة الاجتماعية، عدد المعالين، حالة التوظيف، الدخل، حالة السكن، الوضع المالي) لتخصيص المحتوى\n- اكتب بأسلوب رسمي ومحترم يناسب طلب الدعم الاجتماعي\n- ركز على التفاصيل الواقعية والظروف الحقيقية\n- لا تستخدم الإنجليزية أبداً\n- أنهِ عندما ينتهي الوصف. لا عبارات ختامية، لا "شكراً"، لا خاتمة\n- يجب أن يكون ردك فقط المحتوى المطلوب مكتوباً بصيغة المتكلم، لا شيء آخر`,
    },
  };

  return prompts[language][fieldType];
}
